# Generated by Django 5.1.3 on 2025-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
